POST http://localhost:3000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "firstname": "Bon",
    "lastname": "jour",
    "age": "25",
    "password": "123456"
    "email" : "bruceBanner@marvel.com"
}

###

